# Generated by Django 4.2.4 on 2023-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="reporter_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
