# Generated by Django 4.2.4 on 2023-09-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_ticket_reporter_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="reporter_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tickettype",
            name="reporter_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="reporter_id",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
